### ISSUE TITLE
Mod causes game to crash

### ISSUE THREAD

**Issue by leeterry** [Selim042/SM-Selim-Enchants#6]
Okay, not 100% sure how you can recreate the issue but while I was walking around on my mushroom isle base lightning struck and spawned 4 skeletion riders on skeleton horses a few feet ahead of me (called Skeleton Trap apparently according to google and is a rare occurrence which is what might make it difficult to test without cheating).  Anyway, the game crashed almost instantly and gave a log file. So, I backed up my save, removed all mods, and tried again with only forge loaded but got no crash. I then exit the game, replaced the save files with the backup files I had made, added a mod to the mods folder, and repeated the testing process. This went on a bit till I moved your mod into the folder at which point I got a crash. Therefore I removed all mods except yours and reset everything to make sure it was not conflicting with another mod but still got a crash during the test. For some reason the game stopped giving me log files after the first crash (only got the one that shows all the mods I had been using) but since as I said I tested the other mods (even did a test using all mods but yours) and found it to be your mod that causes the crash. I did upload the log to Pastebin though just in case it was needed (see the bottom of this post) and could give the backup save file if wanted/needed but not sure it will help since you will not be entering the game as my character (let me know if you want the save file).
https://pastebin.com/yBw5YXqF

**Comment by Selim042** [comment]
I will try to take a look soon

**Comment by Selim042** [comment]
Ignore the wrong label business.  That commit should fix it, but there is something else I want to try and work out before releasing the update with this patch.  Going to leave this open so I try and remember to let you know when the update is released.  If that fails, keep an eye on CF.
