### ISSUE TITLE
Server Crash, mentions Selims enchants and silent gems

### ISSUE THREAD

**Issue by Darkmega18** [Selim042/SM-Selim-Enchants#7]
I was just attempted to update my server with my latest transcendence version at long last. but this happens. Versions mentioned are there. And selims is this version: Selim's Enchantments-1.12.2-2.1.0

around half way through multicraft would just restart the loading, meaning something crashed. grabbed the crash log out of the server and this is what I got. I'm sending it to both sides and linking the two issues, hopefully you's can work it all out. :) and let each other know what needs fixing so the mods can work well server side while they seem to be just fine on the client.
Versions of the mods and forge etc used is in the format on Silent's side of the issue if you need them.

https://pastebin.com/WB2cqXUk

Silent's Side:
https://github.com/SilentChaos512/SilentGems/issues/356

**Comment by Selim042** [comment]
That looks almost definitely like it is me.  I can try and take a look this weekend.

**Comment by Selim042** [comment]
Strangely enough, I don't touch ChatFormatting on that line though....hmmm
https://github.com/Selim042/SM-Selim-Enchants/blob/master/src/main/java/selim/selim_enchants/EnchantmentSelim.java#L23

And, I thought this felt familiar, you've opened the same issue before which I thought was addressed https://github.com/Selim042/SM-Selim-Enchants/issues/2

**Comment by SilentChaos512** [comment]
Looks like the fix from #2 was never released? Latest 1.12.2 version on CurseForge is 2.1.0, released Sep 16. Issue #2 was opened and closed on Oct 14.

**Comment by Selim042** [comment]
Oh, that would do it...strange...
I'll look into #6 this weekend and then release the update to (hopefully) fix both

Leaving this open so I don't forget to actually release it this time

**Comment by Darkmega18** [comment]
whoops yeah, I destinctly remember hitting a similar bug from months ago before I disappeared due to burn-out for a while. :V

**Comment by Selim042** [comment]
The update is out on CF now, going to close since I actually remembered to do that this time...

**Comment by Darkmega18** [comment]
ey lmao.

ok, gonna update the pack and give it a go. thanks again. :P

**Comment by Selim042** [comment]
No problem.  Thanks for bringing it up again, otherwise this update probably would have never gone out.... XD
